//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcs.DaemonAutoGeneratedClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelType", Namespace="http://schemas.datacontract.org/2004/07/Parcs")]
    public enum ChannelType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Any = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCP = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NamedPipe = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlSpaceData", Namespace="http://schemas.datacontract.org/2004/07/Parcs.WCF")]
    [System.SerializableAttribute()]
    public partial class ControlSpaceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Parcs.DaemonAutoGeneratedClient.Channel[] ChannelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Parcs.DaemonAutoGeneratedClient.Channel[] Channels {
            get {
                return this.ChannelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelsField, value) != true)) {
                    this.ChannelsField = value;
                    this.RaisePropertyChanged("Channels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/Parcs")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PointIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Parcs.DaemonAutoGeneratedClient.ChannelType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PointID {
            get {
                return this.PointIDField;
            }
            set {
                if ((this.PointIDField.Equals(value) != true)) {
                    this.PointIDField = value;
                    this.RaisePropertyChanged("PointID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Parcs.DaemonAutoGeneratedClient.ChannelType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DaemonAutoGeneratedClient.IDaemonService")]
    public interface IDaemonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaemonService/CreatePont", ReplyAction="http://tempuri.org/IDaemonService/CreatePontResponse")]
        Parcs.DaemonAutoGeneratedClient.Channel CreatePont(string Name, Parcs.DaemonAutoGeneratedClient.ChannelType channelType, Parcs.DaemonAutoGeneratedClient.ControlSpaceData controlSpaceData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaemonService/CreatePont", ReplyAction="http://tempuri.org/IDaemonService/CreatePontResponse")]
        System.Threading.Tasks.Task<Parcs.DaemonAutoGeneratedClient.Channel> CreatePontAsync(string Name, Parcs.DaemonAutoGeneratedClient.ChannelType channelType, Parcs.DaemonAutoGeneratedClient.ControlSpaceData controlSpaceData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaemonService/DestroyControlSpace", ReplyAction="http://tempuri.org/IDaemonService/DestroyControlSpaceResponse")]
        bool DestroyControlSpace(Parcs.DaemonAutoGeneratedClient.ControlSpaceData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDaemonService/DestroyControlSpace", ReplyAction="http://tempuri.org/IDaemonService/DestroyControlSpaceResponse")]
        System.Threading.Tasks.Task<bool> DestroyControlSpaceAsync(Parcs.DaemonAutoGeneratedClient.ControlSpaceData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDaemonServiceChannel : Parcs.DaemonAutoGeneratedClient.IDaemonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DaemonServiceClient : System.ServiceModel.ClientBase<Parcs.DaemonAutoGeneratedClient.IDaemonService>, Parcs.DaemonAutoGeneratedClient.IDaemonService {
        
        public DaemonServiceClient() {
        }
        
        public DaemonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DaemonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaemonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DaemonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Parcs.DaemonAutoGeneratedClient.Channel CreatePont(string Name, Parcs.DaemonAutoGeneratedClient.ChannelType channelType, Parcs.DaemonAutoGeneratedClient.ControlSpaceData controlSpaceData) {
            return base.Channel.CreatePont(Name, channelType, controlSpaceData);
        }
        
        public System.Threading.Tasks.Task<Parcs.DaemonAutoGeneratedClient.Channel> CreatePontAsync(string Name, Parcs.DaemonAutoGeneratedClient.ChannelType channelType, Parcs.DaemonAutoGeneratedClient.ControlSpaceData controlSpaceData) {
            return base.Channel.CreatePontAsync(Name, channelType, controlSpaceData);
        }
        
        public bool DestroyControlSpace(Parcs.DaemonAutoGeneratedClient.ControlSpaceData data) {
            return base.Channel.DestroyControlSpace(data);
        }
        
        public System.Threading.Tasks.Task<bool> DestroyControlSpaceAsync(Parcs.DaemonAutoGeneratedClient.ControlSpaceData data) {
            return base.Channel.DestroyControlSpaceAsync(data);
        }
    }
}
